#!/usr/bin/env python3
"""Reference values for the numpy/pandas-compatible C++ kernels.

Writes cpp/tests/data/numpy_reference.tsv with one check per line:
kind<TAB>input<TAB>expected, floats as Python repr (round-trip exact).
"""
from __future__ import annotations

import io
import sys
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

from cap_guiding.case_metadata import infer_plateau_length_mm_from_text  # noqa: E402

OUT = REPO / "cpp" / "tests" / "data" / "numpy_reference.tsv"

PLATEAU_TEXTS = (
    "003_f20_chan_n4e18cm3_L5mm_foc0um_rz",
    "078_f32_chan_n6e18cm3_L25mm_focp500um_rz/guiding_metrics.csv",
    "C:\\runs\\case_L2p5mm_test",
    "cpp/tests/data/golden/cases/000_f20_chan_n4e18cm3_L2mm_d150um_foc0um_rz/guiding_metrics.csv",
    "caseL3mm",
    "cases L3mm",
    "a sL3mm",
    "a SL3mm",
    "x-L1.5mm-y",
    "L7mm",
    "_l7MM_",
    "_L7mmx",
    "_L7.5.5mm_",
    "_L2P5mm_",
    "_L10p25mm",
    "no plateau here",
    "path/with_L5mm_and_L6mm_",
    "run_L05mm/",
)

PANDAS_TEXTS = (
    "0.9479768899922173",
    "9.884458606166733",
    "0.12345678901234567890123",
    "123456789012345678901234567890",
    "000123.4500",
    "1E5",
    "1e-320",
    "4.9e-324",
    "2.2250738585072014e-308",
    "1.7976931348623157e308",
    "-0.0",
    "+12.5",
    " 7.25 ",
    "5e",
    "1e+",
    ".5",
    "5.",
    "inf",
    "-inf",
    "Infinity",
    "-Infinity",
    "nan",
    "NaN",
    "None",
    "",
    "abc",
    "1e400",
    "0.1e-400",
)


def fmt(values) -> str:
    return " ".join(repr(float(v)) for v in values)


def pandas_cases(rng: np.random.Generator) -> list[str]:
    texts = [repr(float(v)) for v in rng.standard_normal(2500) * 10.0 ** rng.uniform(-30.0, 30.0, 2500)]
    texts += [repr(float(v)) for v in rng.random(500) * 20.0]
    texts += list(PANDAS_TEXTS)
    frame = pd.read_csv(io.StringIO("i,x\n" + "".join(f"{i},{t}\n" for i, t in enumerate(texts))))
    values = pd.to_numeric(frame["x"], errors="coerce").to_numpy(float)
    return [f"pandasfloat\t{text}\t{float(value)!r}" for text, value in zip(texts, values)]


def main() -> None:
    rng = np.random.default_rng(20260915)
    lines = ["# kind\tinput\texpected (generated by tools/golden/make_numpy_reference.py)"]

    for n in (1, 2, 7, 8, 9, 15, 16, 17, 63, 64, 65, 127, 128, 129, 130, 200, 255, 256, 257, 1000):
        x = rng.standard_normal(n) * 10.0 ** rng.uniform(-3.0, 9.0, n)
        lines.append(f"sum64\t{fmt(x)}\t{float(np.sum(x))!r}")
        x32 = x.astype(np.float32)
        lines.append(f"sum32\t{fmt(x32)}\t{float(np.sum(x32))!r}")
        lines.append(f"meansq32\t{fmt(x32)}\t{float(np.mean(x32 * x32))!r}")
        lines.append(f"median\t{fmt(x)}\t{float(np.median(x))!r}")

    for window in range(2, 11):
        y = rng.random(97) * 1.0e13
        smoothed = np.convolve(y, np.ones(window, dtype=float) / window, mode="same")
        lines.append(f"movavg{window}\t{fmt(y)}\t{fmt(smoothed)}")

    for start, stop, n in ((0.0, 1.0, 11), (-3.2e-5, 1.28e-4, 160), (5.4e-3, 5.5272e-3, 160), (1e-6, 3.1e-5, 16),
                           (2.0, 2.0, 5), (0.0, 3.0e-5, 16)):
        lines.append(f"linspace\t{start!r} {stop!r} {n}\t{fmt(np.linspace(start, stop, n))}")

    for value in (0.5, 1.5, 2.5, 3.5, -0.5, -1.5, 2.4999999999999996, 1.0e15 + 0.5, 7.0):
        lines.append(f"round\t{value!r}\t{round(value)}")

    specials = [0.0, -0.0, 1.0, 100.0, 1e15, 1e16, 1e-4, 1e-5, 5e-324, 1.7976931348623157e308, 2.0**0.5,
                123456789012345678.0, 0.1, 1.0 / 3.0, 2.5e-16, 9.999999999999999e-5, 1e22, 12345.678]
    randoms = rng.standard_normal(3000) * 10.0 ** rng.uniform(-30.0, 30.0, 3000)
    for value in specials + [float(v) for v in randoms]:
        lines.append(f"repr\t{float(value).hex()}\t{float(value)!r}")
    for text, value in (("nan", float("nan")), ("inf", float("inf")), ("-inf", float("-inf"))):
        lines.append(f"repr\t{text}\t{value!r}")

    lines += pandas_cases(rng)

    for text in PLATEAU_TEXTS:
        try:
            value = infer_plateau_length_mm_from_text(text)
            expected = "None" if value is None else repr(value)
        except ValueError:
            expected = "ValueError"
        lines.append(f"plateau\t{text}\t{expected}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {len(lines) - 1} reference checks to {OUT}")


if __name__ == "__main__":
    main()
